# auto-generated from v2raytun_core.xlsx (top by frequency, per-cluster -> page)
# regenerate: python gen_related.py  (chips: keyword text only)
RELATED = {
    '/': [
        'V2raytun',
        'V2raytun пк',
        'V2raytun github',
        'V2raytun window',
        'V2 raytun',
        'V2ray tun',
        'V2raytun приложение',
        'V2raytun работает',
        'V2raytune',
        'V2raytun com',
        'V2raytun код',
        'V2raytun коды',
        'V2raytun списки',
        'Сайт v2raytun',
        'V2raytun белые списки',
        'V2raytun белый список',
        'V2raytun тг',
        'Https v2raytun',
        'V2raytun официальный',
        'V2raytun официальный сайт',
        'Коды для v2raytun',
        'V2raytun гитхаб',
        'V2raytun import',
        'V2raytun обход',
        'V2raytun купить',
        'V2raytun рабочие',
        'Https v2raytun com',
        'V2raytun оплатить',
        'V2raytun глушилки',
        'Белый для v2raytun',
        'Белые списки для v2raytun',
        'V2raytun пробный',
        'V2raytun телеграмм',
        'Ссылки для v2raytun',
        'V2raytun файл',
        'V2raytun маршрутизация',
        'V2raytun что это',
        'V2raytun keys',
        'V2raytun обновить',
        'V2raytun версии',
    ],
    '/skachat-v2raytun/': [
        'V2raytun скачать',
        'V2raytun скачать скачать',
        'Скачать v2raytun',
        'Скачать v2raytun скачать',
        'V2raytun скачать пк',
        'V2raytun бесплатно',
        'V2raytun скачать github',
        'V2raytun скачать бесплатно',
        'Скачать приложение v2raytun',
        'V2raytun скачать приложение',
        'Установить v2raytun',
        'V2raytun установить',
        'V2ray tun скачать',
        'V2raytune скачать',
        'V2raytun download',
        'V2raytun скачать гитхаб',
        'V2raytun гитхаб скачать',
        'V2raytun бесплатный код',
        'V2raytun коды бесплатно',
        'V2raytun скачать официальный',
        'V2raytun официальный сайт скачать',
        'V2raytun скачать официальный сайт',
        'V2raytun скачать файл',
        'Бесплатные коды для v2raytun',
        'V2raytun белый список бесплатный',
        'V2raytun free',
        'V2raytun скачать апк',
        'V2raytun апк скачать',
        'V2raytun скачать апк v2raytun',
        'V2raytun скачать торрент',
        'V2raytun скачать тв',
        'Скачайте клиент v2raytun',
        'V2raytun скачать клиент',
        'V2raytun скачать последнюю версию',
        'V2raytun free keys',
        'V2raytun keys free',
        'V2raytun key free',
        'Обход v2raytun бесплатный',
        'V2raytun com скачать',
        'V2raytun скачать на тв',
    ],
    '/podpiska/': [
        'V2raytun прокси',
        'Прокси v2raytun',
        'Прокси для v2raytun',
        'V2raytun прокси бесплатно',
        'Бесплатные прокси v2raytun',
        'Прокси для v2raytun бесплатно',
        'Бесплатные прокси для v2raytun',
        'Бесплатный прокси для v2raytun',
        'V2raytun прокси сервер',
        'V2raytun прокси сервера',
        'Прокси сервер v2raytun',
        'V2raytun proxy',
        'Proxy v2raytun',
        'Прокси сервер для v2raytun',
        'Прокси сервера для v2raytun',
        'Прокси на v2raytun',
        'V2raytun proxy client',
        'V2raytun настройка прокси',
        'Бесплатные прокси сервера для v2raytun',
        'Бесплатный прокси сервер для v2raytun',
        'V2raytun прокси туннель',
        'Прокси v2raytun скачать',
        'V2raytun обнаружены активированные настройки прокси',
        'Обнаружены активированные настройки прокси v2raytun',
        'V2raytun прокси тг',
        'Прокси на v2raytun бесплатно',
        'V2raytun как настроить прокси',
        'Как настроить прокси v2raytun',
        'V2raytun режим прокси',
        'Proxy для v2raytun',
        'V2raytun прокси для тг',
        'Прокси для тг v2raytun',
        'V2raytun прокси или туннель',
    ],
    '/konfigi/': [
        'V2raytun ключи',
        'V2raytun ключ',
        'Ключи для v2raytun',
        'V2raytun ключ бесплатно',
        'V2raytun бесплатно ключ',
        'V2raytun бесплатные ключи',
        'Ключи v2raytun бесплатно',
        'Ключи v2raytun бесплатные',
        'V2raytun конфигурации',
        'V2raytun конфигурация',
        'Бесплатные ключи для v2raytun',
        'Ключи для v2raytun бесплатные',
        'Ключи для v2raytun бесплатно',
        'Подписка v2raytun',
        'V2raytun подписка',
        'Конфигурации для v2raytun',
        'V2raytun подключение',
        'V2raytun ключи подключения',
        'Ключи подключения v2raytun',
        'V2raytun конфиг',
        'V2raytun конфиги',
        'Конфиг v2raytun',
        'V2raytun подключить',
        'Конфиги для v2raytun',
        'Конфиг для v2raytun',
        'V2raytun подключения бесплатно',
        'V2raytun ключи подключения бесплатно',
        'Ключ на v2raytun',
        'Ключи на v2raytun',
        'V2raytun бесплатные конфигурации',
        'V2raytun конфигурации бесплатно',
        'V2raytun конфигурации бесплатные',
        'V2raytun конфигурация бесплатно',
        'Как подключить v2raytun',
        'V2raytun как подключить',
        'V2raytun сервер',
        'V2raytun сервера',
        'V2raytun серверы',
        'Сервера v2raytun',
        'Конфигурации для v2raytun бесплатно',
    ],
    '/podklyuchenie/': [
        'V2raytun настроить',
        'V2raytun как настроить',
        'Как настроить v2raytun',
        'V2raytun как скачать',
        'V2raytun настройка',
        'V2raytun setup',
        'Как оплатить v2raytun',
        'V2raytun setup exe',
        'V2raytun на пк как скачать',
        'Как сделать v2raytun',
        'V2raytun как поделиться',
        'V2raytun как скачать на айфон',
        'V2raytun на айфон как скачать',
        'Как скачать v2raytun на айфон',
        'V2raytun как пользоваться',
        'Storage v2raytun com v2raytun setup exe',
        'Как настроить v2raytun на андроид',
        'Как настроить v2raytun на андроиде',
        'Настройка для v2raytun',
        'Https storage v2raytun com v2raytun setup exe',
        'Как настроить v2raytun на айфон',
        'V2raytun как настроить на айфон',
        'V2raytun как настроить на айфоне',
        'V2raytun на айфон как настроить',
        'Как настроить v2raytun на айфоне',
        'Как настроить приложение v2raytun',
        'V2raytun как настроить маршрутизацию',
        'Как настроить маршрутизацию v2raytun',
        'V2raytun как оплатить без телеграмма',
        'V2raytun как установить на пк',
        'Как установить v2raytun на пк',
        'V2raytun инструкция',
        'V2raytun как настроить на пк',
        'V2raytun на пк как настроить',
        'Как настроить v2raytun на пк',
        'V2raytun настройка маршрутизации',
        'Настройка маршрутизации v2raytun',
        'Как установить v2raytun на айфон',
        'V2raytun как установить на айфон',
        'V2raytun как удалить',
    ],
    '/pk/': [
        'V2raytun на пк',
        'V2raytun скачать на пк',
        'V2raytun на пк скачать',
        'Скачать v2raytun на пк',
        'Скачать v2raytun скачать на пк',
        'V2raytun windows',
        'V2raytun windows скачать',
        'V2raytun скачать windows',
        'V2raytun на пк github',
        'V2raytun скачать на пк github',
        'V2raytun скачать на windows',
        'V2raytun на пк windows',
        'V2raytun скачать на пк windows',
        'V2raytun на пк windows скачать',
        'Бесплатный v2raytun на пк',
        'V2raytun скачать на пк бесплатно',
        'V2raytun скачать бесплатно на пк',
        'Скачать v2raytun на пк бесплатно',
        'V2raytun приложение на пк',
        'Скачать приложение v2raytun на пк',
        'V2raytun скачать на пк приложение',
        'V2raytun скачать приложение на пк',
        'V2raytun exe',
        'V2raytun windows github',
        'V2raytun для пк',
        'V2raytun mac',
        'V2raytun для windows',
        'V2raytun виндовс',
        'V2raytun pc',
        'V2raytun на пк официальный сайт',
        'V2raytun скачать на пк официальный сайт',
        'V2raytun официальный сайт скачать на пк',
        'V2raytun скачать виндовс',
        'V2raytun на пк гитхаб',
        'V2raytun на виндовс',
        'V2raytun на компьютер',
        'V2raytun на компьютере',
        'V2raytun скачать на пк гитхаб',
        'V2raytun mac os',
        'V2raytun macos',
    ],
    '/android/': [
        'V2raytun андроид',
        'V2raytun на андроид',
        'V2raytun андроид скачать',
        'V2raytun скачать андроид',
        'Скачать v2raytun на андроид',
        'V2raytun на андроид скачать',
        'V2raytun скачать на андроид',
        'V2raytun apk',
        'V2raytun apk скачать',
        'V2raytun скачать apk',
        'V2raytun скачать бесплатно на андроид',
        'V2raytun скачать на андроид бесплатно',
        'V2raytun на андроид apk',
        'Скачать v2raytun на андроид apk',
        'V2raytun скачать на андроид apk',
        'V2raytun android',
        'V2raytun на телефон',
        'V2raytun для андроид',
        'V2raytun apk файл',
        'V2raytun apk github',
        'Скачать apk файл v2raytun',
        'V2raytun скачать apk файл',
        'V2raytun андроид тв',
        'V2raytun android apk',
        'V2raytun android tv',
        'V2raytun android скачать',
        'V2raytun скачать бесплатно apk',
        'V2raytun apk скачать бесплатно',
        'V2raytun скачать андроид тв',
        'V2raytun скачать на андроид бесплатно apk',
        'V2raytun на андроид тв',
        'Com v2raytun android',
        'V2raytun tv apk',
        'Скачать приложение v2raytun на андроид',
        'V2raytun скачать приложение на андроид',
        'V2raytun apk 4pda',
        'V2raytun android tv apk',
        'Скачать v2raytun на андроид тв',
        'V2raytun на андроид тв скачать',
        'V2raytun скачать на андроид тв',
    ],
    '/ios/': [
        'V2raytun айфон',
        'V2raytun на айфон',
        'V2raytun скачать айфон',
        'V2raytun скачать на айфон',
        'V2raytun на айфон скачать',
        'V2raytun ios',
        'V2raytun iphone',
        'V2raytun как скачать на айфон',
        'V2raytun на айфон как скачать',
        'Как скачать v2raytun на айфон',
        'V2raytun скачать на айфон бесплатно',
        'V2raytun скачать бесплатно на айфон',
        'V2raytun ios скачать',
        'Как настроить v2raytun на айфон',
        'V2raytun как настроить на айфон',
        'V2raytun на айфон как настроить',
        'V2raytun скачать ios',
        'V2raytun на ios',
        'V2raytun apple',
        'Приложение v2raytun на айфон',
        'Как установить v2raytun на айфон',
        'V2raytun как установить на айфон',
        'V2raytun для ios',
        'Настройка v2raytun iphone',
        'V2raytun скачать на ios',
        'V2raytun приложение ios',
        'V2raytun ключ айфон',
        'V2raytun ключи айфон',
        'V2raytun скачать для айфон',
        'Скачать приложение v2raytun на айфон',
        'V2raytun настройка ios',
        'Маршрутизация v2raytun ios',
        'V2raytun маршрутизация ios',
        'Аналоги v2raytun на айфон',
        'V2raytun аналог на айфон',
        'V2raytun ключи на айфон',
        'V2raytun приложение iphone',
        'Https apps apple com app v2raytun id6476628951',
        'V2raytun есть на айфон',
        'Ключи для v2raytun на айфон',
    ],
    '/tv/': [
        'V2raytun телевизор',
        'V2raytun на телевизор',
        'V2raytun на телевизоре',
        'V2raytun скачать на телевизор',
        'V2raytun на телевизор скачать',
        'Скачать v2raytun на телевизор',
        'V2raytun tv',
        'V2raytun android tv',
        'V2raytun как подключить телевизор',
        'V2raytun для телевизора',
        'V2raytun tv apk',
        'V2raytun android tv apk',
        'V2raytun как подключить на телевизоре',
        'Как подключить v2raytun на телевизоре',
        'V2raytun установить на телевизор',
        'Как установить v2raytun на телевизор',
        'V2raytun tv скачать',
        'V2raytun скачать для телевизора',
        'V2raytun на телевизор lg',
        'V2raytun android tv скачать',
        'V2raytun как импортировать на телевизор',
        'Как активировать v2raytun',
        'V2raytun на телевизор apk',
        'Как импортировать подписку v2raytun на телевизор',
        'V2raytun скачать на телевизор apk',
        'V2raytun tv скачать apk',
        'V2raytun apk android tv скачать',
        'V2raytun apk для телевизора',
        'V2raytun скачать apk android tv',
        'V2raytun обнаружены активированные настройки прокси',
        'Обнаружены активированные настройки прокси v2raytun',
        'V2raytun как добавить на телевизоре',
        'Как подключить v2raytun на телевизоре через телефон',
        'V2raytun скачать на телевизор lg',
        'Как подключить телевизор к v2raytun',
        'Как подключить v2raytun к телевизору',
    ],
    '/problemy/': [
        'Не работает v2raytun',
        'V2raytun не работает',
        'V2raytun почему не работает',
        'V2raytun перестал',
        'V2raytun перестал работать',
        'V2raytun ошибка',
        'V2raytun не работает что делать',
        'V2raytun не работает на айфоне',
        'V2raytun не работает сегодня',
        'V2raytun не работает пк',
        'Не работает v2raytun на пк',
        'V2raytun на пк не работает',
        'V2raytun не работает на пк',
        'Что делать если v2raytun не работает',
        'V2raytun что делать если не работает',
        'V2raytun не работает андроид',
        'V2raytun не работает на андроид',
        'V2raytun не подключается',
        'V2raytun не работает интернет',
        'Почему перестал работать v2raytun',
        'Почему не работает v2raytun на айфоне',
        'V2ray tun не работает',
        'V2raytun ошибка 502',
        'Приложение v2raytun не работает',
        'V2raytun ошибка при импорте конфигурации',
        'V2raytun почему не работает андроид',
        'V2raytun при импорте возникла ошибка',
        'Возникла ошибка при импорте конфигурации v2raytun',
        'V2raytun не работает на телефоне',
        'V2raytun не работает телеграмм',
        'V2raytun не запускается',
        'V2raytun выдает ошибку',
        'V2raytun не работает 2026',
        'V2raytun не работает телеграм',
        'V2raytun перестал работать что делать',
        'V2raytun почему не работает интернет',
        'Почему v2raytun не работает на пк',
        'V2raytun не работает на мобильном интернете',
        'Почему v2raytun не работает на телефоне',
        'V2raytun вылетает',
    ],
    '/faq/': [
        'V2raytun',
        'V2raytun скачать',
        'V2raytun скачать скачать',
        'Скачать v2raytun',
        'Скачать v2raytun скачать',
        'V2raytun пк',
        'V2raytun на пк',
        'V2raytun скачать пк',
        'V2raytun скачать на пк',
        'V2raytun на пк скачать',
        'Скачать v2raytun на пк',
        'Скачать v2raytun скачать на пк',
        'V2raytun ключи',
        'V2raytun ключ',
        'V2raytun бесплатно',
        'Ключи для v2raytun',
        'V2raytun ключ бесплатно',
        'V2raytun бесплатно ключ',
        'V2raytun бесплатные ключи',
        'Ключи v2raytun бесплатно',
        'Ключи v2raytun бесплатные',
        'V2raytun github',
        'V2raytun андроид',
        'V2raytun на андроид',
        'V2raytun андроид скачать',
        'V2raytun скачать андроид',
        'Скачать v2raytun на андроид',
        'V2raytun на андроид скачать',
        'V2raytun скачать на андроид',
        'V2raytun конфигурации',
        'V2raytun конфигурация',
        'V2raytun apk',
        'V2raytun window',
        'V2raytun windows',
        'V2 raytun',
        'Бесплатные ключи для v2raytun',
        'Ключи для v2raytun бесплатные',
        'Ключи для v2raytun бесплатно',
        'V2ray tun',
        'Подписка v2raytun',
    ],
}
